In [1]:
!pip install tensorflow==2.15.0


  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached protobuf-4.25.8-cp310-abi3-win_amd64.whl.metadata (541 bytes)
  Using cached termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached tensorboard-2.15.2-py3-none-any.whl.metadata (1.7 kB)
  Using cached tensorflow_estimator-2.15.0-py2.py3-none-any.whl.metadata (1.3 kB)
  Using cached keras-2.15.0-py3-none-any.whl.metadata (2.4 kB)
  Using cached google_auth-2.45.0-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached google_auth_oauthlib-1.2.3-py3-none-any.whl.metadata (3.1 kB)
  Using

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
### Sentence
sent = ['the glass of milik',
        'the glass of juice',
'the cupof tea',
'I am a good boy',
'I am a good developer',
'understanf the meaning of the word',
'your videos are good']

In [10]:
sent

['the glass of milik',
 'the glass of juice',
 'the cupof tea',
 'I am a good boy',
 'I am a good developer',
 'understanf the meaning of the word',
 'your videos are good']

In [5]:
## Define the vocabulary 
voc_size = 10000

In [ ]:
sent

In [11]:
## One hot Representation 
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2816, 3772, 5806, 804],
 [2816, 3772, 5806, 5499],
 [2816, 3776, 5415],
 [6981, 7637, 3274, 7886, 7177],
 [6981, 7637, 3274, 7886, 9618],
 [1362, 2816, 8256, 5806, 2816, 1846],
 [3651, 5084, 8743, 7886]]

In [15]:
## word Embedding Representation 

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [18]:
import numpy as np
sent_length

8

In [17]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2816 3772 5806  804]
 [   0    0    0    0 2816 3772 5806 5499]
 [   0    0    0    0    0 2816 3776 5415]
 [   0    0    0 6981 7637 3274 7886 7177]
 [   0    0    0 6981 7637 3274 7886 9618]
 [   0    0 1362 2816 8256 5806 2816 1846]
 [   0    0    0    0 3651 5084 8743 7886]]


In [19]:
## feature representation
dim = 10

In [20]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse','accuracy')

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 437ms/step


array([[[ 0.02970829, -0.02430716,  0.00165607, -0.04275695,
          0.02127234,  0.0178269 ,  0.01333163,  0.01183299,
          0.00817551,  0.01402878],
        [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,
          0.02127234,  0.0178269 ,  0.01333163,  0.01183299,
          0.00817551,  0.01402878],
        [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,
          0.02127234,  0.0178269 ,  0.01333163,  0.01183299,
          0.00817551,  0.01402878],
        [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,
          0.02127234,  0.0178269 ,  0.01333163,  0.01183299,
          0.00817551,  0.01402878],
        [ 0.04460254,  0.00099926,  0.03457827,  0.04976488,
         -0.01882999,  0.0493764 , -0.03213118,  0.00617529,
          0.03380967,  0.03095832],
        [ 0.03632785, -0.02414423,  0.01229538,  0.00158978,
          0.02757463, -0.00904034, -0.03547059,  0.0449481 ,
          0.02391228, -0.01556274],
        [-0.0204899 ,  0.02269932, -0.04457694,  0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 2816, 3772, 5806,  804])

In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 57ms/step


array([[ 0.02970829, -0.02430716,  0.00165607, -0.04275695,  0.02127234,
         0.0178269 ,  0.01333163,  0.01183299,  0.00817551,  0.01402878],
       [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,  0.02127234,
         0.0178269 ,  0.01333163,  0.01183299,  0.00817551,  0.01402878],
       [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,  0.02127234,
         0.0178269 ,  0.01333163,  0.01183299,  0.00817551,  0.01402878],
       [ 0.02970829, -0.02430716,  0.00165607, -0.04275695,  0.02127234,
         0.0178269 ,  0.01333163,  0.01183299,  0.00817551,  0.01402878],
       [ 0.04460254,  0.00099926,  0.03457827,  0.04976488, -0.01882999,
         0.0493764 , -0.03213118,  0.00617529,  0.03380967,  0.03095832],
       [ 0.03632785, -0.02414423,  0.01229538,  0.00158978,  0.02757463,
        -0.00904034, -0.03547059,  0.0449481 ,  0.02391228, -0.01556274],
       [-0.0204899 ,  0.02269932, -0.04457694,  0.0343783 , -0.00554664,
         0.04108698,  0.00233023,  0.04122533